#!/usr/bin/env bash
vars+=(
'PROJECT_NAME="Heidi: A Raspberry Pi 3 Development Cluster"'
'PROJECT_AUTHOR="Arron Atchison"'
'PROJECT_AUTHOR_EMAIL="arron.atchison@gmail.com"'
)
source ./env/init_vars

#echo "Exporting Project Vars"
#for i in "${vars[@]}"
#do
#    echo ${i}
#    export "${i}"
#done

#echo ${PROJECT_NAME}
